import fs from 'node:fs';
import { geoConicConformal, geoPath } from 'd3-geo';
import { feature } from 'topojson-client';
import polylabel from 'polylabel';

const DIR = new URL('.', import.meta.url).pathname; // run from tools/ after npm install
const es = JSON.parse(fs.readFileSync(DIR + 'node_modules/es-atlas/es/autonomous_regions.json'));
const world = JSON.parse(fs.readFileSync(DIR + 'node_modules/world-atlas/countries-50m.json'));

const regions = feature(es, es.objects.autonomous_regions).features;
const mainland = { type: 'FeatureCollection', features: regions.filter(f => f.id !== '05') };
const canarias = regions.find(f => f.id === '05');

const W = 1000;
// frame in lon/lat: keep sea on the bottom right for the Canary inset
const frame = { type: 'Feature', geometry: { type: 'MultiPoint', coordinates: [[-9.9, 44.0], [4.7, 44.0], [-9.9, 34.15], [4.7, 34.15], [-3.7, 34.15], [-3.7, 44.05]] } };
const proj = geoConicConformal().parallels([36, 43]).rotate([3.7, 0]).fitWidth(W, frame);
const pathM = geoPath(proj);
const [[fx0, fy0], [fx1, fy1]] = pathM.bounds(frame);
proj.translate([proj.translate()[0] - fx0, proj.translate()[1] - fy0]);
const H = Math.round(fy1 - fy0);
console.error('viewBox', W, H, 'scale', proj.scale());

// Canary inset: same scale, own centre
const projC = geoConicConformal().parallels([27, 30]).rotate([15.8, 0]).scale(proj.scale());
const pathC0 = geoPath(projC);
const cb = pathC0.bounds(canarias);
const cw = cb[1][0] - cb[0][0], ch = cb[1][1] - cb[0][1];
const pad = 22;
const box = { w: Math.round(cw + pad * 2), h: Math.round(ch + pad * 2 + 10) };
box.x = W - box.w - 14; box.y = H - box.h - 14;
projC.translate([projC.translate()[0] - cb[0][0] + box.x + pad, projC.translate()[1] - cb[0][1] + box.y + pad + 10]);
console.error('canary box', box, 'canary size', cw.toFixed(0), ch.toFixed(0));

const r1 = x => Math.round(x * 10) / 10;
const fmt = d => d.replace(/-?\d+\.\d+/g, m => String(r1(+m)));

function labelPoint(f, pj) {
  const polys = f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates;
  let best = null, bestA = -1;
  for (const p of polys) {
    const ring = p.map(r => r.map(c => pj(c)));
    const a = Math.abs(ring[0].reduce((s, c, i, arr) => { const n = arr[(i + 1) % arr.length]; return s + c[0] * n[1] - n[0] * c[1]; }, 0) / 2);
    if (a > bestA) { bestA = a; best = ring; }
  }
  const lp = polylabel(best, 0.5);
  return [r1(lp[0]), r1(lp[1])];
}

const out = { W, H, box, regions: [], neighbors: [] };
for (const f of regions) {
  const isC = f.id === '05';
  const pth = isC ? geoPath(projC) : pathM;
  const pj = isC ? projC : proj;
  out.regions.push({ id: f.id, src: f.properties.name, d: fmt(pth(f)), lp: labelPoint(f, pj), c: pth.centroid(f).map(r1), b: pth.bounds(f).map(p => p.map(r1)), area: Math.round(pth.area(f)) });
}

// neighbours, clipped to the frame
const projN = geoConicConformal().parallels([36, 43]).rotate([3.7, 0]).scale(proj.scale()).translate(proj.translate()).clipExtent([[-5, -5], [W + 5, H + 5]]);
const pathN = geoPath(projN);
const countries = feature(world, world.objects.countries).features;
for (const name of ['Portugal', 'France', 'Andorra', 'Morocco', 'Algeria', 'United Kingdom']) {
  const f = countries.find(c => c.properties.name === name);
  if (!f) { console.error('missing', name); continue; }
  const d = pathN(f);
  if (d) out.neighbors.push({ name, d: fmt(d) });
}
fs.writeFileSync(DIR + '../map-data.js', '// Generated by tools/build-map.mjs. Do not edit by hand.\nwindow.MAP_DATA = ' + JSON.stringify(out) + ';\n');
for (const r of out.regions) console.error(r.id, r.src, 'lp', r.lp, 'area', r.area, 'len', r.d.length);
console.error('neighbors', out.neighbors.map(n => n.name + ':' + n.d.length).join(' '));
console.error('total', fs.statSync(DIR + '../map-data.js').size);
